### ISSUE TITLE
Script gives error

### ISSUE THREAD

**Issue by AlawamiAZ** [Cristi075/HG658b_data_dumper#3]
What is the problem here?

ali@pop-os:~/Downloads/HG658b_data_dumper-master$ python2 dump_data.py
No target provided. Trying to use the default gateway (192.168.1.1)
Trying to obtain the config file by using a path traversal ...
Config file obtained.
Traceback (most recent call last):
  File "dump_data.py", line 236, in <module>
    config_data = get_config(args.target)
  File "dump_data.py", line 198, in get_config
    tree = etree.fromstring(xml_data)
  File "src/lxml/etree.pyx", line 3227, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1871, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1752, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1066, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 598, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 709, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 638, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

**Comment by Cristi075** [comment]
It looks like config that was dumped is not a well-formed XML document.
Could you post the first lines of the resulting document?

Ex: add a print statement and print xml_data on line 196.
Maybe there are some slight differences than what I was encountering on my router.
